package com.finalso.data;
// Generated 05-may-2018 23:22:58 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Partidos generated by hbm2java
 */
@Entity
@Table(name = "partidos", catalog = "mlb")
public class Partidos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4889533422909351346L;
	private String id;
	private Date fecha;
	private String equipoLocal;
	private String equipoVisitante;
	private String marcador;

	public Partidos() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "Equipo_local", length = 100)
	public String getEquipoLocal() {
		return this.equipoLocal;
	}

	public void setEquipoLocal(String equipoLocal) {
		this.equipoLocal = equipoLocal;
	}

	@Column(name = "Equipo_visitante", length = 100)
	public String getEquipoVisitante() {
		return this.equipoVisitante;
	}

	public void setEquipoVisitante(String equipoVisitante) {
		this.equipoVisitante = equipoVisitante;
	}

	@Column(name = "Marcador", length = 100)
	public String getMarcador() {
		return this.marcador;
	}

	public void setMarcador(String marcador) {
		this.marcador = marcador;
	}

}
